### PR TITLE
Update libraries and refactor some code

### PR DESCRIPTION
**Pull request by johannesE**
Hi Rafał, thanks for the great library.
Please take a look at my changes and give me some feedback. Every commit message should describe what I did.
I did not change the changelog or version.
Best regards,
Joe

### CODE REVIEW

**Comment by Kociamber** [comment]
Hi Joe,
Thank you for your contribution! I will go through the changes and will
come back to you asap :)
Cheers,
Rafał

sob., 1 sie 2020 o 15:51 Johannes <notifications@github.com> napisał(a):

**Comment by johannesE** [comment]
Sorry, did not see that there is someone alive here 😅
I had already planned to take over the repo..

**Comment by Kociamber** [comment]
OMG I've just noticed the date! I'm really sorry for the late answer -
somehow my smtp client filtered out ALL github messages :D
I'm definitely alive and to be honest was also planning to update few of my
libs so you have great timing :)
There is something I need to finish here but I already started checking
your changes, I will merge your PR and we can continue maintaining it
together :) Are you using it in your smart farming project?
Cheers,
Rafał

czw., 4 mar 2021 o 15:55 Johannes <notifications@github.com> napisał(a):

**Comment by johannesE** [comment]
Hi Kociamber
Yes, I'm using it there at https://databaum.ch :-)
It works pretty well actually.
Best regards,
Joe

**Pull request merged**
